### ISSUE TITLE
After going through nether portal right eye is blocked and has black screen

### ISSUE THREAD

**Issue by jmacadude** [jrbudda/Vivecraft_111#17]
After going through a nether portal the right eye on the vive shows up as all black/brown with some texture.  Left eye is clear and working fine.  In main menu both eyes work correctly

**Comment by jrbudda** [comment]
Not been able to reproduce this, are you using shaders, or a texture pack or any non-default video options?

**Comment by DragonicNick** [comment]
I've got the same problem on the 1.7.10 version with a lot of mods.
I don't have the problem on the 1.11.2 version.

**Comment by ranavi** [comment]
Could it be related to this? https://bugs.mojang.com/browse/MC-98153
IIRC they "fixed" it by adding immunity when going through then nether portal, but you still briefly appear at the wrong coordinates, which can be inside a wall. That said, I'm not a developer and have no idea if it could cause this kind of issues.

I can't test it myself, because i don't own a VR headset. But there's couple things you can try.
Write down the nether portal coordinates in overworld, go to nether and clear the area around those coordinates.
Alternatively if you are not experiencing the bug, go to those coordinates and fill it with blocks.

**Comment by jrbudda** [comment]
Gonna assume fixed.
