### ISSUE TITLE
Right directional control options missing

### ISSUE THREAD

**Issue by cdfdman** [jrbudda/Vivecraft_111#21]
There are currently no right hand controller directional options in the controller settings. Ie Left, Right, Up and Down. Using Oculus touch, I cannot change what the directional commands from the thumb stick. Please add those additional options if possible so that I may remap them to my preferences. (Thank you for all of your hard work, this mod is awesome!)

**Comment by jrbudda** [comment]
The right thumbstick is currently hard-coded to hotbar and inventory scrolling. It's not re-bindable because those functions are not the same as other commands and wouldn't work with the rebinding system. I intend on fixing that at some point but I couldn't say when, the up/down menu scrolling is particularly complicated because of the mouse emulation.
